name: Build iOS dylib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      # මෙතන v3 වෙනුවට v4 දැම්මා
      uses: actions/checkout@v4

    - name: Configure CMake for iOS
      run: cmake -B build -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0

    - name: Build dylib
      run: cmake --build build --config Release

    - name: Upload Artifact
      # මෙතනත් v3 වෙනුවට v4 දැම්මා
      uses: actions/upload-artifact@v4
      with:
        name: MyModMenu-iOS-Library
        path: build/Release-iphoneos/libMyModMenu.dylib